name: iOS CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    if: ${{ github.ref_name == github.event.repository.default_branch || github.event_name == 'pull_request' }}
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Setup Xcode (latest stable)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # SwiftLint を brew で叩くだけ（プラグインは無視）
      - name: Install tools
        run: |
          brew install swiftlint || true
          brew install xcpretty || true
      - name: SwiftLint
        run: swiftlint --strict || true

      # SPM パッケージ単体テスト
      - name: SwiftPM Package Test (APIModule)
        working-directory: APIModule
        run: swift test -v

      # アプリのビルド＆テスト（1回でまとめる）
      - name: Build and test App
        run: |
          xcodebuild test \
            -project APIClientSample.xcodeproj \
            -scheme APIClientSample \
            -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16 Pro' \
            -enableCodeCoverage YES \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO \
          | xcpretty
