name: iOS CI

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build-and-test:
    if: ${{ github.ref_name == github.event.repository.default_branch || github.event_name == 'pull_request' }}
    runs-on: macos-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      # 2. DerivedData をキャッシュ
      - name: Cache DerivedData
        uses: actions/cache@v4.2.3
        with:
          path: ~/Library/Developer/Xcode/DerivedData
          key: ${{ runner.os }}-xcode-derived-${{ hashFiles('**/*.swift') }}
          restore-keys: |
            ${{ runner.os }}-xcode-derived-

      # 3. Xcode のセットアップ
      - name: Setup Xcode (latest stable)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      # 4. SPM 依存解決（Xcodeプロジェクト）
      - name: Resolve Swift Packages
        run: |
          xcodebuild \
            -project APIClientSample.xcodeproj \
            -resolvePackageDependencies

      # 4.5 SwiftPM パッケージ単体テスト（APIModule）
      - name: SwiftPM Package Test (APIModule)
        working-directory: APIModule
        run: swift test -v

      # 5. ビルド
      - name: Build (with SwiftLint if enabled)
        run: |
          xcodebuild build \
            -project APIClientSample.xcodeproj \
            -scheme APIClientSample \
            -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16 Pro' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
          | xcpretty

      # 6. ビルド&テスト
      - name: Build and test
        run: |
          xcodebuild test \
            -project APIClientSample.xcodeproj \
            -scheme APIClientSample \
            -destination 'platform=iOS Simulator,OS=18.5,name=iPhone 16 Pro' \
            -enableCodeCoverage YES \
          | xcpretty
